### ISSUE TITLE
Multiple tracks same conference

### ISSUE THREAD

**Issue by sivanahamer** [se-deadlines/se-deadlines.github.io#1]
Many software engineering venues have multiple tracks. For example:
- Research track/full paper track
- Short paper
- Industry tack
- Journal first track
- Tools tracks
- Dataset tracks
- New and emerging ideas track

We could probably, to make it easier to add and find tracks, add a tag to be added when adding an entry. An example how it would look would be the following:

```
- name: ICSE-JF
  description: International Conference on Software Engineering - Journal-first Papers
  year: 2025
  link: https://conf.researchr.org/track/icse-2025/icse-2025-journal-first-papers
  deadline: 
  - "2024-10-21 23:59"
  date: April 26 - May 4, 2025
  place: Ottawa, Ontario, Canada
  tags: [CO]
  tracks: [JF]
```

**Comment by imranur-rahman** [comment]
I agree with the idea. It could be something similar to tags. Will have time to work on this after next week.

**Comment by sivanahamer** [comment]
Well, the good news is there are tracks with the data. Now, we need to see how we reduce the tags, as there are like a lot of them: 
![image](https://github.com/se-deadlines/se-deadlines.github.io/assets/20550496/153b02c9-2e44-4e00-ba00-2e7bf4250f13)

**Comment by imranur-rahman** [comment]
How about we group these?

- Type of Proceeding
    - Conference
    - Journal
    - Workshop
- Type of paper submission track
    - Research Paper Track
    - Short Paper Track
    - In Practice Track
    - Society Track
    - Education Track
    - Journal First Track
    - Tool Track
    - New Ideas and Emerging Results Track
    - Registered Reports Track
- Others
    - Artifact Track
    - Doctoral Symposium
    - New Faculty Symposium
    - Student Research Competition
    - Late Breaking Track
    - Challenge Track
    - Tutorials and Technical Briefings Track
    - Experience Papers Track
    - Replicability Studies Track

**Comment by sivanahamer** [comment]
Hi!

I like the idea and groups. I would put everything with tracks as track and
name other as “Other submissions”.  How would this look? Also, I assume you
are working on this then?

**Comment by imranur-rahman** [comment]
Yes, I will be working on this. But still trying to figure out what is a better way to present to the viewers. I can come up with couple and maybe then we decide which one to use.

**Comment by sivanahamer** [comment]
I say go for whatever setup you want and we can always improve it :)

**Comment by imranur-rahman** [comment]
Just pushed one [commit](https://github.com/se-deadlines/se-deadlines.github.io/commit/0393bf3bdf28f58d204e0868a3f2f0bb4c71394b) to group by venue, track and others.
