### ISSUE TITLE
Separate abstract and full paper submission deadline

### ISSUE THREAD

**Issue by imranur-rahman** [se-deadlines/se-deadlines.github.io#2]
Many SE conferences follow separate deadlines for abstract and full paper submission within the same track deadline. For example, this years ICSE research track has abstract submission deadline on Mar 15 AoE and full paper submission deadline on Mar 22.

In the current setting, we only show the abstract submission deadline in our website but not the full paper submission deadline. We should think of some way to handle this.

**Comment by sivanahamer** [comment]
OMG I was thinking the same thing lol. It’s hard to know if we should put the abstract deadline or the final one. 

I have two solutions in mind for now:
1. We could add a flag in the ‘.yml’ entry so we specify that there is an earlier required abstract submission.  For example it could be like ‘abstract-deadline: true’ or ‘abstract-deadline: 1 week’.
2. The second would be to add a second date format type of thing in the entry. With this we could add multiple entries in the deadline list, though we would need a way to group them up with the deadlines.

Personally, I like the first one a bit more. Though, I am also open to new ideas for this.

**Comment by sivanahamer** [comment]
The [HCI deadline page](https://hci-deadlines.github.io/) has a note tag:

```yml
...
note: Text about something important
...
```

It seems like the easiest way to add this.

**Comment by sivanahamer** [comment]
I will try to do this one as it is easy this week :)

**Comment by sivanahamer** [comment]
Hmmm, the note entry is not appearing...

**Comment by sivanahamer** [comment]
Works now. If we want to update later on how we want this to look, we can do so.
