### ISSUE TITLE
Categorizing conferences according to tiers.

### ISSUE THREAD

**Issue by imranur-rahman** [se-deadlines/se-deadlines.github.io#9]
It might be worthwhile to categorize the conferences into tiers (e.g., icse and fse into tier 1). One might want to submit their papers to a certain tiered conference. But it would be hard to justify our choice of a conference being in a certain tier. And it would be biased by our personal opinion and taste. On top of that, multiple tracks add complexity to this tiered system (e.g., do you consider icse-seip as tier 1 or not?).

But I am putting it here to hear your thoughts, @sivanahamer, and those of anyone else's.

**Comment by sivanahamer** [comment]
I would hold against the idea for now: 
1. I think already, with the tracks, having tiers would be a lot of information on the page.
2. You can get an updated list of general tiers from Google Scholar: https://scholar.google.com/citations?view_op=top_venues&hl=en&vq=eng_softwaresystems. Or also with: https://portal.core.edu.au/conf-ranks/. So, we would need to provide additional value to the tiers on our page that are not provided in other sources.
3. Even with tiers, some venues specialize in specific topics. Thus, "tiers" are highly context-dependent.
4. I assume that deadline pages do not have tier information for similar reasons.

**Comment by sivanahamer** [comment]
Oh, and also, I do not know how we would tier workshops, different tracks within the same conference, or special calls for papers in journals.

**Comment by imranur-rahman** [comment]
That's fair. I am closing this issue, then. Thanks!
